name: Run 25 times a day

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow
  schedule:
    # Runs every 2 minutes
    - cron: '*/2 * * * *'  # Run every 2 minutes
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  run-workflows:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow the GitHub token to push changes
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git author identity
      run: |
        git config --global user.email "vaibhavwateam@gmail.com"
        git config --global user.name "ShubhamRon"

    - name: Set up environment
      run: |
        echo "Setting up environment"
        sudo apt-get update
        sudo apt-get install -y git  # Ensure git is installed
        sudo chmod +x setup.sh  # Make the setup.sh script executable

    - name: Configure Git with PAT
      run: |
        git remote set-url origin https://github.com/${{ github.repository }}.git
        git config --global credential.helper store
        echo "https://${{ secrets.GH_TOKEN }}:@github.com" > ~/.git-credentials

    - name: Run custom script
      run: |
        echo "Running setup script..."
        ./setup.sh
