name: Run 25 times a day

on:
  schedule:
    - cron: '*/2 * * * *'  # Run every 2 minutes
    - cron: '*/3 * * * *'  # Run every 3 minutes
    - cron: '*/4 * * * *'  # Run every 4 minutes
    - cron: '*/5 * * * *'  # Run every 5 minutes
    
jobs:
  run-workflows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run custom script
      run: |
        echo "Running workflow..."
        sudo chmod +x setup.sh
        ./setup.sh
